# Generated by Django 5.0.4 on 2025-01-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'Director'), ('team_leader', 'Team Leader'), ('admin', 'Admin')], default='team_leader', max_length=20),
        ),
    ]
