# Generated by Django 4.2.9 on 2025-01-17 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin_number', models.CharField(max_length=50, unique=True)),
                ('manager_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('company_type', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=20)),
                ('organization', models.CharField(max_length=100)),
                ('performance', models.TextField()),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('year', models.IntegerField()),
                ('categories', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='work_registration.company')),
            ],
        ),
    ]
