# Generated by Django 4.2.9 on 2025-01-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_registration', '0002_company_approved_project_remark_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='year',
        ),
    ]
