# Generated by Django 4.2.9 on 2025-01-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_registration', '0003_remove_project_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='remark',
            new_name='project_remark',
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
