# Generated by Django 5.0.4 on 2025-01-26 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_registration', '0005_company_forwarded_by_company_forwarded_to_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
