# Generated by Django 5.0.4 on 2025-01-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_registration', '0009_alter_company_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
