# Generated by Django 4.2.9 on 2025-01-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_registration', '0011_alter_company_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('finished', 'Completed'), ('unfinished', 'Unfinished'), ('ongoing', 'Ongoing')], default='unfinished', max_length=50),
        ),
    ]
