# Generated by Django 4.2.9 on 2025-01-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_registration', '0012_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
